"""${m}

Revision ID: 21115bc93eda
Revises: 259855d03638
Create Date: 2026-03-03 06:21:28.948108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21115bc93eda'
down_revision = '259855d03638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
