"""新增ppx_config_var表

Revision ID: 259855d03638
Revises: 88b0c291da2e
Create Date: 2026-03-03 06:17:42.550463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259855d03638'
down_revision = '88b0c291da2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppx_config_var',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppx_config_var_key'), 'ppx_config_var', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ppx_config_var_key'), table_name='ppx_config_var')
    op.drop_table('ppx_config_var')
    # ### end Alembic commands ###
