"""${m}

Revision ID: 44a7785024f6
Revises: c63cade9c229
Create Date: 2026-03-16 00:01:23.390039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a7785024f6'
down_revision = 'c63cade9c229'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
