"""更新ppx_storage_var表字段

Revision ID: 5906e4bc71c2
Revises: 802ec4ff5306
Create Date: 2026-03-03 02:27:23.800689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5906e4bc71c2'
down_revision = '802ec4ff5306'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppx_storage_var', sa.Column('sku', sa.String(), nullable=False))
    op.add_column('ppx_storage_var', sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('ppx_storage_var', sa.Column('star', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('ppx_storage_var', sa.Column('status', sa.Integer(), server_default='0', nullable=False))
    op.drop_index('ix_ppx_storage_var_key', table_name='ppx_storage_var')
    op.create_index(op.f('ix_ppx_storage_var_sku'), 'ppx_storage_var', ['sku'], unique=True)
    op.drop_column('ppx_storage_var', 'remark')
    op.drop_column('ppx_storage_var', 'val')
    op.drop_column('ppx_storage_var', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppx_storage_var', sa.Column('key', sa.VARCHAR(), nullable=False))
    op.add_column('ppx_storage_var', sa.Column('val', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False))
    op.add_column('ppx_storage_var', sa.Column('remark', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False))
    op.drop_index(op.f('ix_ppx_storage_var_sku'), table_name='ppx_storage_var')
    op.create_index('ix_ppx_storage_var_key', 'ppx_storage_var', ['key'], unique=False)
    op.drop_column('ppx_storage_var', 'status')
    op.drop_column('ppx_storage_var', 'star')
    op.drop_column('ppx_storage_var', 'price')
    op.drop_column('ppx_storage_var', 'sku')
    # ### end Alembic commands ###
