"""${m}

Revision ID: 594595075a53
Revises: e18815479f93
Create Date: 2026-03-15 23:16:23.411190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594595075a53'
down_revision = 'e18815479f93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppx_storage_var', sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppx_storage_var', 'comment_count')
    # ### end Alembic commands ###
