"""${m}

Revision ID: 63c9e5a5d4c1
Revises: 6df4ae2d9e1d
Create Date: 2026-03-16 00:02:39.104257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c9e5a5d4c1'
down_revision = '6df4ae2d9e1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
