"""${m}

Revision ID: 6c5c671a37cc
Revises: 5906e4bc71c2
Create Date: 2026-03-03 02:39:15.704722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5c671a37cc'
down_revision = '5906e4bc71c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
