"""${m}

Revision ID: 6df4ae2d9e1d
Revises: 44a7785024f6
Create Date: 2026-03-16 00:02:03.097674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df4ae2d9e1d'
down_revision = '44a7785024f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
