"""${m}

Revision ID: 77e45e7937d4
Revises: cc82b18290d9
Create Date: 2026-03-16 00:00:26.604896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e45e7937d4'
down_revision = 'cc82b18290d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
