"""${m}

Revision ID: 88b0c291da2e
Revises: 6c5c671a37cc
Create Date: 2026-03-03 02:39:27.352781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b0c291da2e'
down_revision = '6c5c671a37cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
