"""${m}

Revision ID: b14d43f063f4
Revises: 21115bc93eda
Create Date: 2026-03-03 06:21:39.939336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14d43f063f4'
down_revision = '21115bc93eda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
