"""${m}

Revision ID: c63cade9c229
Revises: 77e45e7937d4
Create Date: 2026-03-16 00:01:08.532221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63cade9c229'
down_revision = '77e45e7937d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
