"""${m}

Revision ID: cc82b18290d9
Revises: 42f5695aeffb
Create Date: 2026-03-15 23:28:44.679703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc82b18290d9'
down_revision = '42f5695aeffb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
